test suite: avoid exception when TMPDIR isn't set (#411)
'env' lookup returns an empty string when the environment variable
isn't defined, hence 'path' parameter wasn't omitted.

The exception was:
docker.errors.APIError: 500 Server Error: Internal Server Error (\"create ansible.jpz85xs2ubuntu/test-ubuntu: \"ansible.jpz85xs2ubuntu/test-ubuntu\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intented to pass a host directory, use absolute path\")"